telegraf:
  image: telegraf:1.14.1-alpine
  container_name: telegraf
  hostname: cassandra1
#  set appopriate ips
  extra_hosts:
    - "influxdb:10.2.2.5"
    - "hostip:10.2.2.6"
  volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - /var/run/docker.sock:/var/run/docker.sock
