version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - http.cors.enabled=true
      - http.cors.allow-origin=/.*/
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      - ./jvm.options:/usr/share/elasticsearch/config/jvm.options
    ports:
      - 9200:9200
    networks:
      - elastic

  es_vue:
    image: cars10/elasticvue
    ports:
      - 12332:8080
volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
