version: '3'
services:
  mongodb:
    image: mongo:3
    restart: always
    volumes:
      - /data2/graylog/mongo:/data/db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    restart: always
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
  graylog:
    image: graylog/graylog:3.0
    restart: always
    environment:
      - GRAYLOG_PASSWORD_SECRET=mfyz11sanane22banan
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a91
      - GRAYLOG_HTTP_EXTERNAL_URI=http://${HOST}:9000/
    links:
      - mongodb:mongo
      - elasticsearch
    volumes:
      - /opt/graylog/graylog/graylog-plugin-slack-3.1.0.jar:/usr/share/graylog/plugin/graylog-plugin-slack-3.1.0.jar
      - /opt/graylog/graylog/graylog-plugin-input-jmx-1.0.2-SNAPSHOT.jar:/usr/share/graylog/plugin/graylog-plugin-input-jmx-1.0.2-SNAPSHOT.jar
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      - 9000:9000 # Graylog web interface and REST API
      - 5555:5555 # Raw/Plaintext TCP
      - 1514:1514 # Syslog TCP
      - 1514:1514/udp # Syslog UDP
      - 12201:12201 # GELF TCP
      - 12201:12201/udp # GELF UDP

volumes:
  esdata:
