version: '3'
services:
  # Configuration for our seed cassandra node. The node is call DC1N1
  # .i.e Node 1 in Data center 1.
  DC1N1:
    # Cassandra image for Cassandra version 3.11.1. This is pulled
    # from the docker store.
    image: cassandra:3.11.1
    # In case this is the first time starting up cassandra we need to ensure
    # that all nodes do not start up at the same time. Cassandra has a
    # 2 minute rule i.e. 2 minutes between each node boot up. Booting up
    # nodes simultaneously is a mistake. This only needs to happen the firt
    # time we bootup. Configuration below assumes if the Cassandra data
    # directory is empty it means that we are starting up for the first
    # time.
    command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 0; fi && /docker-entrypoint.sh cassandra -f'
    # Network for the nodes to communicate
    networks:
      - dc1ring
    # Maps cassandra data to a local folder. This preserves data across
    # container restarts. Note a folder n1data get created locally
    volumes:
      - ./n1data:/var/lib/cassandra
    # Docker constainer environment variable. We are using the
    # CASSANDRA_CLUSTER_NAME to name the cluster. This needs to be the same
    # across clusters. We are also declaring that DC1N1 is a seed node.
    environment:
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_CLUSTER_NAME=dev_cluster
    # Exposing ports for inter cluste communication
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    # Cassandra ulimt recommended settings
    ports:
      - "9042:9042"
      - "7199:7199"
    ulimits:
      memlock: -1
      nproc: 32768
      nofile: 100000



networks:
  dc1ring:
